server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: petshop-cep-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:petshop_db}}
    username: ${DB_USERNAME:petshop_user}
    password: ${DB_PASSWORD:petshop_password}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  docker:
    compose:
      lifecycle-management: start-only

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
    address: ${MANAGEMENT_SERVER_ADDRESS:127.0.0.1}
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

info:
  app:
    name: Petshop CEP API
    description: API REST para consulta de CEP em serviço externo mockado, com persistência de logs e arquitetura baseada em SOLID.
    version: 0.0.1-SNAPSHOT

app:
  cep:
    base-url: ${CEP_API_BASE_URL:?CEP_API_BASE_URL é obrigatorio}
    connect-timeout: 2s
    read-timeout: 3s